const fs = require('fs');
const R = '\uFFFD';
const RR = R+R;
const RRR = R+R+R;
const RRRR = R+R+R+R;

let c = fs.readFileSync('c:/esolucoesia.com/dfe/src/components/NfceDashboard.tsx', 'utf8');

const fixes = [
  ['Configura'+RRRR+'es', 'Configurações'],
  ['configura'+RRRR+'es', 'configurações'],
  ['Al'+R+'quotas de Transi'+RR+'o', 'Alíquotas de Transição'],
  ['Al'+R+'quota de Cr'+R+'dito', 'Alíquota de Crédito'],
  ['Al'+R+'quotas CBS', 'Alíquotas CBS'],
  ['Al'+R+'quotas', 'Alíquotas'],
  ['Al'+R+'quota', 'Alíquota'],
  ['al'+R+'quotas', 'alíquotas'],
  ['al'+R+'quota', 'alíquota'],
  ['Alimenta'+RR+'o', 'Alimentação'],
  ['alimenta'+RR+'o', 'alimentação'],
  ['Altera'+RR+'o', 'Alteração'],
  ['altera'+RR+'o', 'alteração'],
  ['Amap'+R, 'Amapá'],
  ['At'+R+' ', 'Até '],
  ['A'+RR+'o Inv'+R+'lida', 'Ação Inválida'],
  ['A'+RR+'o', 'Ação'],
  ['a'+RR+'o', 'ação'],
  ['autua'+RR+'o', 'autuação'],
  ['adi'+RR+'o de item', 'adição de item'],
  ['Bot'+R+'es principais', 'Botões principais'],
  ['Bot'+R+'es', 'Botões'],
  ['bot'+R+'es', 'botões'],
  ['bot'+R+'o', 'botão'],
  ['Ci'+R+'ncia da Opera'+RR+'o', 'Ciência da Operação'],
  ['Opera'+RR+'o', 'Operação'],
  ['opera'+RR+'o', 'operação'],
  ['Ci'+R+'ncia', 'Ciência'],
  ['ci'+R+'ncia', 'ciência'],
  ['Combust'+R+'vel', 'Combustível'],
  ['combust'+R+'vel', 'combustível'],
  ['Conclu'+R+'da', 'Concluída'],
  ['conclu'+R+'da', 'concluída'],
  ['inclu'+R+'dos', 'incluídos'],
  ['inclu'+R+'do', 'incluído'],
  ['Condi'+RR+'es de pagamento', 'Condições de pagamento'],
  ['Condi'+RR+'es', 'Condições'],
  ['condi'+RR+'es', 'condições'],
  ['Conex'+R+'o', 'Conexão'],
  ['conex'+R+'o', 'conexão'],
  ['Configura'+RR+'o', 'Configuração'],
  ['configura'+RR+'o', 'configuração'],
  ['comunica'+RR+'o ao emitir', 'comunicação ao emitir'],
  ['comunica'+RR+'o', 'comunicação'],
  ['Comunica'+RR+'o', 'Comunicação'],
  ['Cr'+R+'dito Loja', 'Crédito Loja'],
  ['Cart'+R+'o Cr'+R+'dito', 'Cartão Crédito'],
  ['Cart'+R+'o D'+R+'bito', 'Cartão Débito'],
  ['Cart'+R+'o', 'Cartão'],
  ['cart'+R+'o', 'cartão'],
  ['Cr'+R+'dito', 'Crédito'],
  ['cr'+R+'dito', 'crédito'],
  ['C'+R+'d. Munic'+R+'pio', 'Cód. Município'],
  ['C'+R+'d.', 'Cód.'],
  ['C'+R+'digo', 'Código'],
  ['c'+R+'digo', 'código'],
  ['c'+R+' ', 'cá '],
  ['come'+R+'ar', 'começar'],
  ['Cear'+R, 'Ceará'],
  ['descri'+RR+'o', 'descrição'],
  ['Destinat'+R+'rio', 'Destinatário'],
  ['destinat'+R+'rio', 'destinatário'],
  ['Devolu'+RR+'o Emitida', 'Devolução Emitida'],
  ['Devolu'+RR+'o de Venda', 'Devolução de Venda'],
  ['Devolu'+RR+'o de mercadoria', 'Devolução de mercadoria'],
  ['Devolu'+RR+'o', 'Devolução'],
  ['devolu'+RR+'o', 'devolução'],
  ['Distribui'+RR+'o DF', 'Distribuição DF'],
  ['Edi'+RR+'o de Item', 'Edição de Item'],
  ['edi'+RR+'o', 'edição'],
  ['Endere'+R+'o e Contato', 'Endereço e Contato'],
  ['Endere'+R+'o', 'Endereço'],
  ['endere'+R+'o', 'endereço'],
  ['Esp'+R+'rito Santo', 'Espírito Santo'],
  ['Exclus'+R+'o', 'Exclusão'],
  ['exclus'+R+'o', 'exclusão'],
  ['Exclu'+R+'da', 'Excluída'],
  ['exclu'+R+'da', 'excluída'],
  ['Exclu'+R+'do', 'Excluído'],
  ['exclu'+R+'do', 'excluído'],
  ['espa'+R+'o reservado', 'espaço reservado'],
  ['espa'+R+'o', 'espaço'],
  ['est'+R+'o salvas', 'estão salvas'],
  ['est'+R+'o', 'estão'],
  ['est'+R+' ', 'está '],
  ['For'+R+'ar NFePHP', 'Forçar NFePHP'],
  ['For'+R+'a atualiza', 'Força atualiza'],
  ['For'+R+'a aba', 'Força aba'],
  ['for'+R+'a aba', 'força aba'],
  ['For'+R+'ar', 'Forçar'],
  ['for'+R+'ar', 'forçar'],
  ['Gerar'+R+' NF', 'Gerará NF'],
  ['gerar'+R, 'gerará'],
  ['Goi'+R+'s', 'Goiás'],
  ['Importa'+RR+'o', 'Importação'],
  ['importa'+RR+'o', 'importação'],
  ['Informa'+RR+'es Adicionais', 'Informações Adicionais'],
  ['Informa'+RR+'es', 'Informações'],
  ['informa'+RR+'es', 'informações'],
  ['informa'+RR+'o', 'informação'],
  ['Inscri'+RR+'o Estadual', 'Inscrição Estadual'],
  ['Inscri'+RR+'o', 'Inscrição'],
  ['inscri'+RR+'o', 'inscrição'],
  ['Integra'+RR+'o SMARTPOS', 'Integração SMARTPOS'],
  ['Integra'+RR+'o', 'Integração'],
  ['integra'+RR+'o', 'integração'],
  ['Inv'+R+'lida', 'Inválida'],
  ['Inv'+R+'lido', 'Inválido'],
  ['inv'+R+'lido', 'inválido'],
  ['inv'+R+'lida', 'inválida'],
  ['In'+R+'cio', 'Início'],
  ['in'+R+'cio', 'início'],
  ['Maranh'+R+'o', 'Maranhão'],
  ['maranh'+R+'o', 'maranhão'],
  ['Munic'+R+'pio IBGE', 'Município IBGE'],
  ['Munic'+R+'pio', 'Município'],
  ['munic'+R+'pios quando', 'municípios quando'],
  ['munic'+R+'pios', 'municípios'],
  ['munic'+R+'pio', 'município'],
  ['M'+R+'quina', 'Máquina'],
  ['m'+R+'nimo', 'mínimo'],
  ['m'+R+'ximo', 'máximo'],
  ['navega'+RR+'o', 'navegação'],
  ['N'+R+'o foi poss'+R+'vel', 'Não foi possível'],
  ['N'+R+'o h'+R, 'Não há'],
  ['N'+R+'o', 'Não'],
  ['n'+R+'o h'+R+' notas', 'não há notas'],
  ['n'+R+'o h'+R+' UF', 'não há UF'],
  ['n'+R+'o h'+R, 'não há'],
  ['n'+R+'o feche', 'não feche'],
  ['n'+R+'o identificado', 'não identificado'],
  ['n'+R+'o configurada', 'não configurada'],
  ['n'+R+'o est'+R, 'não está'],
  ['n'+R+'o pode', 'não pode'],
  ['n'+R+'o possui', 'não possui'],
  ['n'+R+'o '+R+' JSON', 'não é JSON'],
  ['n'+R+'o', 'não'],
  ['nº'+R, 'nº'],
  ['Observa'+RR+'es', 'Observações'],
  ['Observa'+RR+'o', 'Observação'],
  ['observa'+RR+'es', 'observações'],
  ['observa'+RR+'o', 'observação'],
  ['obrigat'+R+'ria para novo', 'obrigatória para novo'],
  ['obrigat'+R+'ria', 'obrigatória'],
  ['obrigat'+R+'rios', 'obrigatórios'],
  ['obrigat'+R+'rio', 'obrigatório'],
  ['or'+R+'amento n'+R+'o possui', 'orçamento não possui'],
  ['or'+R+'amento encontrado', 'orçamento encontrado'],
  ['or'+R+'amento no per'+R+'odo', 'orçamento no período'],
  ['or'+R+'amento ou nome', 'orçamento ou nome'],
  ['or'+R+'amento', 'orçamento'],
  ['Paran'+R, 'Paraná'],
  ['Para'+R+'ba', 'Paraíba'],
  ['Par'+R+' ', 'Pará '],
  ['Par'+R+'metros', 'Parâmetros'],
  ['par'+R+'metros', 'parâmetros'],
  ['Piau'+R, 'Piauí'],
  ['per'+R+'odo', 'período'],
  ['poss'+R+'vel', 'possível'],
  ['Poss'+R+'vel', 'Possível'],
  ['Pr'+R+'pria Empresa', 'Própria Empresa'],
  ['pr'+R+'pria empresa', 'própria empresa'],
  ['pr'+R+'pria', 'própria'],
  ['pr'+R+'- ', 'pré-'],
  ['Pr'+R+'via', 'Prévia'],
  ['Raz'+R+'o Social', 'Razão Social'],
  ['raz'+R+'o social', 'razão social'],
  ['raz'+R+'o', 'razão'],
  ['Recupera'+RR+'o de pagamento', 'Recuperação de pagamento'],
  ['recupera'+RR+'o', 'recuperação'],
  ['Refei'+RR+'o', 'Refeição'],
  ['relat'+R+'rio', 'relatório'],
  ['reprova'+RR+'o deste pr'+R, 'reprovação deste pré'],
  ['reprova'+RR+'o', 'reprovação'],
  ['requisi'+RR+'o', 'requisição'],
  ['S'+R+'o Paulo', 'São Paulo'],
  ['s'+R+'o Paulo', 'são Paulo'],
  ['S'+R+'rie obrigat'+R+'rio', 'Série obrigatório'],
  ['S'+R+'rie', 'Série'],
  ['s'+R+'rie', 'série'],
  ['solicita'+RR+'o encontrada', 'solicitação encontrada'],
  ['solicita'+RR+'o', 'solicitação'],
  ['Servi'+R+'os', 'Serviços'],
  ['servi'+R+'os', 'serviços'],
  ['servi'+R+'o n'+R+'o', 'serviço não'],
  ['servi'+R+'o', 'serviço'],
  ['ser'+R+' mantido no hist', 'será mantido no hist'],
  ['ser'+R+'o ignorados', 'serão ignorados'],
  ['ser'+R+' ', 'será '],
  ['Tribut'+R+'ria', 'Tributária'],
  ['Tribut'+R+'rio', 'Tributário'],
  ['tribut'+R+'ria', 'tributária'],
  ['tribut'+R+'rio', 'tributário'],
  ['Unit'+R+'rio', 'Unitário'],
  ['unit'+R+'rio', 'unitário'],
  ['Usu'+R+'rio SMTP', 'Usuário SMTP'],
  ['Usu'+R+'rios', 'Usuários'],
  ['Usu'+R+'rio', 'Usuário'],
  ['usu'+R+'rios', 'usuários'],
  ['usu'+R+'rio', 'usuário'],
  ['vis'+R+'vel', 'visível'],
  ['ap'+R+'s emiss', 'após emiss'],
  ['ap'+R+'s a autoriza', 'após a autoriza'],
  ['ap'+R+'s refresh', 'após refresh'],
  ['ap'+R+'s reload', 'após reload'],
  ['ap'+R+'s ', 'após '],
  ['hist'+R+'rico', 'histórico'],
  ['h'+R+' ${', 'há ${'],
  ['h'+R+' ', 'há '],
  [' '+R+' de ', ' é de '],
  [' '+R+' JSON', ' é JSON'],
  [' '+R+' ', ' é '],
  ['pr'+R+'cadastro', 'pré-cadastro'],
  ['pr'+R+'-', 'pré-'],
  // Remaining patterns missed (RR not RRRR)
  ['Configura'+RR+'es', 'Configurações'],
  ['configura'+RR+'es', 'configurações'],
  ['Solicita'+RR+'es de Acesso', 'Solicitações de Acesso'],
  ['solicita'+RR+'es', 'solicitações'],
  ['Respons'+R+'vel', 'Responsável'],
  ['respons'+R+'vel', 'responsável'],
  ['Seguran'+R+'a', 'Segurança'],
  ['seguran'+R+'a', 'segurança'],
  ['At'+R+':', 'Até:'],
  ['At'+R+'.', 'Até.'],
  ['Ser'+R+' emitida', 'Será emitida'],
  ['Ser'+R+' informada', 'Será informada'],
  ['c'+R+'d. de barras', 'cód. de barras'],
  ['padr'+R+'o', 'padrão'],
  ['v'+R+'lidos', 'válidos'],
  ['j'+R+' h', 'já h'],
  ['emiss'+R+'o', 'emissão'],
  ['Emiss'+R+'o', 'Emissão'],
  ['Par'+R+"'", "Pará'"],
  ['emite'+R, 'emitirá'],
  ['valida'+RR+'o', 'validação'],
  ['Valida'+RR+'o', 'Validação'],
  ['transmiss'+RR+'o', 'transmissão'],
  ['Transmiss'+RR+'o', 'Transmissão'],
  ['autoriza'+RR+'o', 'autorização'],
  ['Autoriza'+RR+'o', 'Autorização'],
  ['autentica'+RR+'o', 'autenticação'],
  // Em dash sequences (corrupted —)
  ['\uFFFD\u00E2\u201A\u00AC\u00E2\u20AC\u009D', ' — '],
  // Bullet point (corrupted •)
  ['\uFFFD\u00E2\u201A\u00AC\u00C2\u00A2', '•'],
  // Back arrow ‹ Voltar (corrupted)
  ['\uFFFD\u00E2\u20AC\u00A0\u00C2\u0090', '‹'],
  // Edit pencil button icon (blue button in ReformaTributaria)
  ['\uFFFD\u00C5\u201C\u00C5\u00BD', '✏'],
  // Delete X button icon (red button in ReformaTributaria)
  ['\uFFFD\u00C5\u201C\u00E2\u20AC\u00A2', '✕'],
  // Remaining Serviço cases
  ['Servi\uFFFDo', 'Serviço'],
  ['servi\uFFFDo', 'serviço'],
  // Bot?o remaining
  ['Bot\uFFFDo', 'Botão'],
  ['bot\uFFFDo', 'botão'],
];

let before = (c.match(/\uFFFD/g)||[]).length;
for(const [bad, good] of fixes) {
  c = c.split(bad).join(good);
}
let after = (c.match(/\uFFFD/g)||[]).length;

// Fix garbled em dash/arrow sequences visible to users (not just in comments)
// These appear as â€" or similar in the source - fix the ones in JSX strings
c = c.split('\u00e2\u0080\u0094').join('—');
c = c.split('\u00e2\u0080\u0093').join('–');

console.log('Replacement chars — Before:', before, '| After:', after, '| Fixed:', before-after);
fs.writeFileSync('c:/esolucoesia.com/dfe/src/components/NfceDashboard.tsx', c, 'utf8');
console.log('Done.');
